from typing import Protocol

class LoggerProtocol(Protocol):
    

    def debug(self, *args,**kwargs) -> None:
        ...
    def info(self, *args,**kwargs) -> None:
        ...
    def warning(self, *args,**kwargs) -> None:
        ...
    def error(self, *args,**kwargs) -> None:
        ...
    def critical(self, *args,**kwargs) -> None:
        ...
